import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import nodemailer from 'nodemailer';
import { validationResult } from 'express-validator';
import * as users from '../models/userModel.js';
import { generateToken } from '../utils/generateToken.js';
import pool from '../config/db.js';

const replyValidation = (req, res) => { const errors = validationResult(req); if (!errors.isEmpty()) { res.status(422).json({ message: errors.array()[0].msg, errors: errors.array() }); return true; } return false; };
export const register = async (req,res) => { if (replyValidation(req,res)) return; try { if (await users.findByEmail(req.body.email)) return res.status(409).json({message:'An account with this email already exists.'}); const result = await users.create({...req.body,password_hash:await bcrypt.hash(req.body.password,10)}); const user = await users.findPublicById(result.insertId); res.status(201).json({message:'Account created successfully.',token:generateToken(user),user}); } catch (e) { res.status(500).json({message:e.code==='ER_DUP_ENTRY'?'This NID is already registered.':'Unable to create account.'}); } };
export const login = async (req,res) => { if (replyValidation(req,res)) return; try { const user = await users.findByEmail(req.body.email); if (!user || !(await bcrypt.compare(req.body.password,user.password_hash))) return res.status(401).json({message:'Incorrect email or password.'}); const publicUser = await users.findPublicById(user.user_id); res.json({token:generateToken(publicUser),user:publicUser}); } catch { res.status(500).json({message:'Unable to authenticate right now.'}); } };
export const profile = async (req,res) => { const user=await users.findPublicById(req.user.user_id); user ? res.json(user) : res.status(404).json({message:'Profile not found.'}); };
export const updateProfile = async (req,res) => { const { full_name, phone_number, profile_image } = req.body; if (!full_name?.trim() || !phone_number?.trim()) return res.status(400).json({message:'Name and mobile number are required.'}); if (profile_image && (!profile_image.startsWith('data:image/') || profile_image.length > 2_800_000)) return res.status(400).json({message:'Use an image under 2 MB.'}); try { await users.updateProfile(req.user.user_id, { full_name: full_name.trim(), phone_number: phone_number.trim(), profile_image }); res.json(await users.findPublicById(req.user.user_id)); } catch { res.status(500).json({message:'Profile could not be updated.'}); } };

const createMailer = () => process.env.SMTP_USER && process.env.SMTP_PASS ? nodemailer.createTransport({ service: 'gmail', auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS } }) : null;
export const forgotPassword = async (req,res) => { if (replyValidation(req,res)) return; const email=req.body.email.trim().toLowerCase(); try { const user=await users.findByEmail(email); if (!user) return res.status(404).json({message:'No account was found with this email address.'}); const mailer=createMailer(); if (!mailer) return res.status(503).json({message:'Email service is not configured. Add SMTP_USER and SMTP_PASS to backend/.env.'}); const code=String(crypto.randomInt(100000,1000000)); await pool.execute('INSERT INTO password_reset_tokens (user_id,code_hash,expires_at) VALUES (?,?,DATE_ADD(NOW(),INTERVAL 10 MINUTE)) ON DUPLICATE KEY UPDATE code_hash=VALUES(code_hash),expires_at=VALUES(expires_at),attempts=0',[user.user_id,await bcrypt.hash(code,10)]); await mailer.sendMail({from:`ReliefConnect BD <${process.env.SMTP_USER}>`,to:email,subject:'Your ReliefConnect password reset code',text:`Your password reset code is ${code}. It expires in 10 minutes. If you did not request it, ignore this email.`}); res.json({message:'A 6-digit verification code has been sent to your email.'}); } catch(e) { console.error('Password reset email failed:',e.message); res.status(502).json({message:'Unable to send the verification email. Check the Gmail SMTP settings and try again.'}); } };
export const resetPassword = async (req,res) => { if (replyValidation(req,res)) return; try { const user=await users.findByEmail(req.body.email.trim().toLowerCase()); if (!user) return res.status(400).json({message:'Invalid or expired verification code.'}); const [rows]=await pool.execute('SELECT * FROM password_reset_tokens WHERE user_id=? AND expires_at > NOW()',[user.user_id]); const token=rows[0]; if (!token || token.attempts>=5 || !(await bcrypt.compare(String(req.body.code),token.code_hash))) { if(token) await pool.execute('UPDATE password_reset_tokens SET attempts=attempts+1 WHERE user_id=?',[user.user_id]); return res.status(400).json({message:'Invalid or expired verification code.'}); } await users.updatePassword(user.user_id,await bcrypt.hash(req.body.password,10)); await pool.execute('DELETE FROM password_reset_tokens WHERE user_id=?',[user.user_id]); res.json({message:'Your password has been updated. You can now sign in.'}); } catch(e) { console.error('Password reset failed:',e.message); res.status(500).json({message:'Unable to reset password right now.'}); } };
